
package co.edu.eam.pa.interbancariows;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InterbancarioWS", targetNamespace = "http://www.eam.edu.co/interbancario", wsdlLocation = "http://104.197.238.134:8080/interbancario/InterbancarioWS?wsdl")
public class InterbancarioWS_Service
    extends Service
{

    private final static URL INTERBANCARIOWS_WSDL_LOCATION;
    private final static WebServiceException INTERBANCARIOWS_EXCEPTION;
    private final static QName INTERBANCARIOWS_QNAME = new QName("http://www.eam.edu.co/interbancario", "InterbancarioWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://104.197.238.134:8080/interbancario/InterbancarioWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INTERBANCARIOWS_WSDL_LOCATION = url;
        INTERBANCARIOWS_EXCEPTION = e;
    }

    public InterbancarioWS_Service() {
        super(__getWsdlLocation(), INTERBANCARIOWS_QNAME);
    }

    public InterbancarioWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INTERBANCARIOWS_QNAME, features);
    }

    public InterbancarioWS_Service(URL wsdlLocation) {
        super(wsdlLocation, INTERBANCARIOWS_QNAME);
    }

    public InterbancarioWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INTERBANCARIOWS_QNAME, features);
    }

    public InterbancarioWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterbancarioWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InterbancarioWS
     */
    @WebEndpoint(name = "InterbancarioWSPort")
    public InterbancarioWS getInterbancarioWSPort() {
        return super.getPort(new QName("http://www.eam.edu.co/interbancario", "InterbancarioWSPort"), InterbancarioWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterbancarioWS
     */
    @WebEndpoint(name = "InterbancarioWSPort")
    public InterbancarioWS getInterbancarioWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.eam.edu.co/interbancario", "InterbancarioWSPort"), InterbancarioWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INTERBANCARIOWS_EXCEPTION!= null) {
            throw INTERBANCARIOWS_EXCEPTION;
        }
        return INTERBANCARIOWS_WSDL_LOCATION;
    }

}
