
package co.edu.eam.pa.clientews;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "notificaciones", targetNamespace = "http://www.eam.edu.co/notificaciones")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Notificaciones {


    /**
     * 
     * @param correo
     * @return
     *     returns co.edu.eam.pa.clientews.RespuestaNotificacion
     */
    @WebMethod(action = "enviarMail")
    @WebResult(name = "RespuestaNotificacion", targetNamespace = "")
    @RequestWrapper(localName = "enviarMail", targetNamespace = "http://www.eam.edu.co/notificaciones", className = "co.edu.eam.pa.clientews.EnviarMail")
    @ResponseWrapper(localName = "enviarMailResponse", targetNamespace = "http://www.eam.edu.co/notificaciones", className = "co.edu.eam.pa.clientews.EnviarMailResponse")
    public RespuestaNotificacion enviarMail(
        @WebParam(name = "correo", targetNamespace = "")
        Mail correo);

    /**
     * 
     * @param sms
     * @return
     *     returns co.edu.eam.pa.clientews.RespuestaNotificacion
     */
    @WebMethod(action = "enviarSMS")
    @WebResult(name = "RespuestaNotificacion", targetNamespace = "")
    @RequestWrapper(localName = "enviarSMS", targetNamespace = "http://www.eam.edu.co/notificaciones", className = "co.edu.eam.pa.clientews.EnviarSMS")
    @ResponseWrapper(localName = "enviarSMSResponse", targetNamespace = "http://www.eam.edu.co/notificaciones", className = "co.edu.eam.pa.clientews.EnviarSMSResponse")
    public RespuestaNotificacion enviarSMS(
        @WebParam(name = "sms", targetNamespace = "")
        Sms sms);

}
